[program:cora-agent]
command=/home/cora/current/cora-agent -config.file=/home/cora/config/agent.yml
directory=/home/cora/data/agent
user=cora
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=3
startretries=5
stopsignal=TERM
stopwaitsecs=15
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/home/cora/logs/cora-agent.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
