[program:cora-server]
command=/opt/cora/bin/cora-server -config.file=/etc/cora/server.yml
directory=/var/lib/cora
user=cora
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=3
startretries=5
stopsignal=TERM
stopwaitsecs=15
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/cora/server.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
