[program:cora-agent]
command=/opt/cora/bin/cora-agent -config.file=/etc/cora-agent/agent.yml
directory=/var/lib/cora-agent
user=cora
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=3
startretries=5
stopsignal=TERM
stopwaitsecs=15
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/cora/agent.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
